version: "3.7"

networks:
  server-net:

volumes:
  mysql-data:

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: ask-a-doc-server
    restart: unless-stopped
    ports: ['8000:8080']
    environment:
      - PORT=8080
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html

    networks:
      server-net:

  # ------------------------

  mysql:
    image: mysql:5.7
    container_name: learnify-learniform-mysql
    restart: unless-stopped
    ports: ['3306:3306']
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel_db
      - MYSQL_PASSWORD=root

    networks:
      server-net:

